language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
sudo: false
install:
- pip install -r requirements.txt
- pip freeze
script: nosetests
after_success: coveralls
deploy:
  provider: pypi
  user: __token__
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
